services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omie-validator-app
    env_file:
      - .env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run dev -- --hostname 0.0.0.0
    restart: unless-stopped