CREATE TABLE IF NOT EXISTS metas_macro (
  id SERIAL PRIMARY KEY,
  segmento VARCHAR(20) NOT NULL CHECK (segmento IN ('imoveis', 'veiculos')),
  mes_referencia DATE NOT NULL,
  meta_estoque_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  meta_financeira_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  meta_pv_total INTEGER NOT NULL DEFAULT 0,
  faturamento_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estoque_usados NUMERIC(14, 2) NOT NULL DEFAULT 0,
  acrescimo_usados NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estoque_carregado_mes NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estoque_a_carregar NUMERIC(14, 2) NOT NULL DEFAULT 0,
  estoque_saiu NUMERIC(14, 2) NOT NULL DEFAULT 0,
  clientes_ativos INTEGER NOT NULL DEFAULT 0,
  cancelamentos_pv INTEGER NOT NULL DEFAULT 0,
  cancelamentos_valor NUMERIC(14, 2) NOT NULL DEFAULT 0,
  ficha_lancamento INTEGER NOT NULL DEFAULT 0,
  vendidas INTEGER NOT NULL DEFAULT 0,
  acrescimo_lancamentos INTEGER NOT NULL DEFAULT 0,
  headcount_ideal INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (segmento, mes_referencia)
);
